# Your Solution
version: '3'
services:

  book_catalog:
    image: book_catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
      - "4001:80"
    environment:
      - DATABASE_URL=postgresql://sit722_10_2hd_user:n5OmHpht6jKxGhXZatjHEuyT9DxWwMRG@dpg-crukk3tumphs73ep5bj0-a.oregon-postgres.render.com/sit722_10_2hd

  inventory_management:
    image: inventory_management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
      - "4002:80"
    environment:
      - DATABASE_URL=postgresql://sit722_10_2hd_user:n5OmHpht6jKxGhXZatjHEuyT9DxWwMRG@dpg-crukk3tumphs73ep5bj0-a.oregon-postgres.render.com/sit722_10_2hd
